version: '3.9'
services:
  sleeping-server:
    image: sleepingmc
    ports:
      - '25565:25565'
      - '19132:19132/udp'
      - '19132:19132/tcp'
    build:
      dockerfile: Dockerfile
    volumes:
      - "./server:/server"
      - "./papermc.sh:/depencencies/papermc.sh"
    restart: unless-stopped
    environment:
      - 'MC_VERSION=${MC_VERSION}'
      - 'PAPER_BUILD=${PAPER_BUILD}'
      - 'AUTO_UPDATE=${AUTO_UPDATE}'
