version: '3.9'
services:
  sleeping-server:
    image: sleepingmctest
    ports:
      - '25565:25565'
    build:
      dockerfile: Dockerfile
    volumes:
      - "server-volume:/server"
    restart: unless-stopped

volumes:
  server-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server
    external: false